[INFO   ] Logger: Record log in /storage/emulated/0/kivy/fest_app_home/.kivy/logs/kivy_19-03-09_29.txt
[INFO   ] Kivy: v1.10.1.dev0, git-ae3665c, 20180425
[INFO   ] Python: v3.6.2 (default, Apr 25 2018, 09:37:02) 
[GCC 7.2.0]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] KivyMD: KivyMD version: 0.1.2
[INFO   ] Text: Provider: sdl2
[INFO   ] OSC: using <thread> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 v1.r18p0-00cet0.31096d938f6f64bb2ec1de8405ab6460'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-T880'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <8192>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[INFO   ] Video: Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
[INFO   ] Loader: using a thread pool of 2 workers
[WARNING] Base: Unknown <android> provider
[INFO   ] Base: Start application main loop
[WARNING] GL: Unpack subimage support is not available
[WARNING] Base: Failed to import "android" module. Could not remove android presplash.
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[CRITICAL] Clock: Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
[WARNING] stderr:     six.raise_from(e, None)
[WARNING] stderr:   File "<string>", line 2, in raise_from
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
[WARNING] stderr:     httplib_response = conn.getresponse()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/http/client.py", line 1331, in getresponse
[WARNING] stderr:     response.begin()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/http/client.py", line 297, in begin
[WARNING] stderr:     version, status, reason = self._read_status()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/http/client.py", line 258, in _read_status
[WARNING] stderr:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/socket.py", line 586, in readinto
[WARNING] stderr:     return self._sock.recv_into(b)
[WARNING] stderr: socket.timeout: timed out
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
[WARNING] stderr:     timeout=timeout
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
[WARNING] stderr:     _stacktrace=sys.exc_info()[2])
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
[WARNING] stderr:     raise six.reraise(type(error), error, _stacktrace)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
[WARNING] stderr:     raise value
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
[WARNING] stderr:     chunked=chunked)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
[WARNING] stderr:     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
[WARNING] stderr:     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
[WARNING] stderr: urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='c.tile.openstreetmap.org', port=80): Read timed out. (read timeout=5)
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/kivy/fest_app_home/mapview/downloader.py", line 102, in _check_executor
[WARNING] stderr:     result = future.result()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/concurrent/futures/_base.py", line 398, in result
[WARNING] stderr:     return self.__get_result()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
[WARNING] stderr:     raise self._exception
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/concurrent/futures/thread.py", line 55, in run
[WARNING] stderr:     result = self.fn(*self.args, **self.kwargs)
[WARNING] stderr:   File "/storage/emulated/0/kivy/fest_app_home/mapview/downloader.py", line 84, in _load_tile
[WARNING] stderr:     req = requests.get(uri, timeout=5)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/api.py", line 75, in get
[WARNING] stderr:     return request('get', url, params=params, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/api.py", line 60, in request
[WARNING] stderr:     return session.request(method=method, url=url, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
[WARNING] stderr:     resp = self.send(prep, **send_kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
[WARNING] stderr:     r = adapter.send(request, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
[WARNING] stderr:     raise ReadTimeout(e, request=request)
[WARNING] stderr: requests.exceptions.ReadTimeout: HTTPConnectionPool(host='c.tile.openstreetmap.org', port=80): Read timed out. (read timeout=5)
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
[WARNING] stderr:     six.raise_from(e, None)
[WARNING] stderr:   File "<string>", line 2, in raise_from
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
[WARNING] stderr:     httplib_response = conn.getresponse()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/http/client.py", line 1331, in getresponse
[WARNING] stderr:     response.begin()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/http/client.py", line 297, in begin
[WARNING] stderr:     version, status, reason = self._read_status()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/http/client.py", line 258, in _read_status
[WARNING] stderr:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/socket.py", line 586, in readinto
[WARNING] stderr:     return self._sock.recv_into(b)
[WARNING] stderr: socket.timeout: timed out
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
[WARNING] stderr:     timeout=timeout
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
[WARNING] stderr:     _stacktrace=sys.exc_info()[2])
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
[WARNING] stderr:     raise six.reraise(type(error), error, _stacktrace)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
[WARNING] stderr:     raise value
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
[WARNING] stderr:     chunked=chunked)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
[WARNING] stderr:     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
[WARNING] stderr:     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
[WARNING] stderr: urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='b.tile.openstreetmap.org', port=80): Read timed out. (read timeout=5)
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/kivy/fest_app_home/mapview/downloader.py", line 102, in _check_executor
[WARNING] stderr:     result = future.result()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/concurrent/futures/_base.py", line 398, in result
[WARNING] stderr:     return self.__get_result()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
[WARNING] stderr:     raise self._exception
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/concurrent/futures/thread.py", line 55, in run
[WARNING] stderr:     result = self.fn(*self.args, **self.kwargs)
[WARNING] stderr:   File "/storage/emulated/0/kivy/fest_app_home/mapview/downloader.py", line 84, in _load_tile
[WARNING] stderr:     req = requests.get(uri, timeout=5)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/api.py", line 75, in get
[WARNING] stderr:     return request('get', url, params=params, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/api.py", line 60, in request
[WARNING] stderr:     return session.request(method=method, url=url, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
[WARNING] stderr:     resp = self.send(prep, **send_kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
[WARNING] stderr:     r = adapter.send(request, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
[WARNING] stderr:     raise ReadTimeout(e, request=request)
[WARNING] stderr: requests.exceptions.ReadTimeout: HTTPConnectionPool(host='b.tile.openstreetmap.org', port=80): Read timed out. (read timeout=5)
[INFO   ] Base: Leaving application in progress...
